- pubsubx/inmemory.go
- pubsubx/kafka.go
- pubsubx/pubsub.go
Abstract subscribers grouping so we don't depend on kafka directly.
Tried with alpha tag `v0.0.15-alpha`.
> Add group functionality to subscribers

- .github/workflows/test.yml
- configx/provider_watch_test.go
- errorx/error.go
- errorx/error_test.go
- go.mod
I've added new function to accept a formatted message for all our relevant error types as well as marked our NewXError function as deprecated in favour of those new functions. I've also removed the `New` keyword as it does not follow golang standard for this specific use case
> feat: migrate new error to error with format

- .github/semantic.yml
- arangox/migrator.go
- elasticx/index_test.go
- elasticx/migrate/migration_test.go
- elasticx/migrate/migrator.go
Add support for scoped migrations so that we can separate dynamic migrations by package across the same engine
> chore: Support scoped migrations

- configx/provider.go
- configx/schema.go
- otelx/config_test.go
- otelx/jaeger.go
- otelx/otel.go
- otelx/otel_test.go
- otelx/otlp.go
- otelx/stdout.go
- otelx/tracer.go
- otelx/tracer.schema.json
- otelx/tracer_config.go
- otelx/tracer_test.go
This PR implement a OTEL struct type which contains the tracer, it will allow in a next PR to add meter in the Otel struct.
- Move Tracer implementation in own folder + add test for the GRPC (only http was implemented which is not the one we use in atlas)
- Rename tracer specific config to allow implement of meter.
> feat: [PROD-3870] Setup otelm and move tracer

- arangox/migration_test.go
- arangox/migrator.go
- pubsubx/config.go
- pubsubx/config.schema.json
- pubsubx/inmemory.go
- pubsubx/kafka.go
- pubsubx/pubsub.go
I've finally moved the scoped config inside our pubsub package which makes it cleaner and removes some bugs related the pointers and channels.
I've also fixed our arango migrations package so that the down migrations properly manage the versioned documents.
> fix: arango migrations down not removing version record document & scoped pubsub

- arangox/migrator.go
This PR fixes a bug in the method createCollectionIfNotExist() of the migrator. This method used an overly complicated custom collectionExists() that was causing issues if collections were deleted in parallel. It now uses directly `m.db.CollectionExists(ctx, name)`
> fix: arangox collection exists

- logrusx/helper.go
This PR implements changes in logrusx, use l.Entry.WithContext(ctx) instead of l.Logger.WithContext(ctx) which overwrited the Entry info
> feat: [ENG-673] Update logrux WithContext

- arangox/migration.go
- arangox/migration_test.go
- arangox/migrator.go
- elasticx/migrate/migration.go
- elasticx/migrate/migration_test.go
- elasticx/migrate/migrator.go
- mathx/clamp.go
- mathx/clamp_test.go
This PR modifies the pattern used for running migrations; Instead of passing `n` migrations to execute (Up or Down), the caller should now provide a `targetVersion` to migrate up or down to.
Turns out the elasticx migrator was not functioning at all for down migrations as we were calling a `setVersion` instead of removing the down-ed version.
> feat: [ENG-740] Change migrator usage

- logrusx/logrus.go
This PR implements a multi-writer in logger with a write_to_file option. It allows in atlas (if set) to have the logs available in Loki and link to traces. The main purpose is for local development and debugging.
> feat: logrusx add option to write_to_file

- logrusx/helper.go
- logrusx/logrus.go
- logrusx/logrus_test.go
Currently, the sensitive headers used in our http request logging were not configurable. This lets us configure it on initialization and dynamically.
> feat: Add configurable sensitive headers

- .github/workflows/release.yml
The release CI was taking the latest tag even if it was on a separate branch.
> fix: Release CI

- testx/http.go
Quick PR to allow setting http headers in `testx.{Verb}Json` methods.
> feat: Add options to allow setting headers in testx

- errorx/error.go
- errorx/error_test.go
This PR adds in Clinia Error struct a details property which would contain all errors that caused the root error
> feat: [ENG-1233] Add details property in Clinia error

- pubsubx/inmemory/pubsub.go
- pubsubx/kgox/consumer.go
- pubsubx/mocks/Subscriber.go
- pubsubx/subscriber.go
- pubsubx/subscriber_error.go
This PR adds some health checks for the subscribers in `pubsubx`. It also adds a short exponential backoff to retry handlers' failures that are retryable.
> feat: [ENG-1454] Health checks

- elasticx/delete_query_response.go
- elasticx/index.go
- elasticx/index_impl.go
- elasticx/index_test.go
This PR adds the capability to pass in a JSON string query to a new API to allow the document deletion matching the query `DeleteQueryDocuments`. The JSON input is the elastic search QSL but under the go-lang struct format. Since this task can includes multiple match, it allows the configuration of ASYNC or SYNC execution and the retrieval of the TaskId to check on the progress of the ASYNC task.
> feat: query delete documents

- internal/tracex/stack.go
- logrusx/helper.go
- pubsubx/kgox/consumer.go
- pubsubx/kgox/consumer_test.go
- testx/buffer.go
- tracex/recover.go
- tracex/recover_test.go
This PR fixes the retry mechanism for our consumer. We had a maxElapsedTime defined, but we really want to retry up to `maxRetryCount` times instead, defining a maximum interval between retries.
This also includes a stack trace log when panics occur for easier debugging.
> fix: Consumer retries

- configx/options.go
- configx/provider.go
- logrusx/config_test.go
- logrusx/helper.go
- logrusx/logrus_test.go
- pubsubx/kgox/consumer.go
- tracex/recover.go
- tracex/recover_test.go
Quick PR that will prevent us from calling the non-`f` logging methods (`Error, Info, Warn, etc.`). These methods do not include the SpanID and TraceID, therefore making correlation between logs and spans very difficult.
> fix: Hide logger methods without span/trace contexts

- pubsubx/config.go
- pubsubx/kgox/pubsub.go
This PR modifies the pubsub opts so send the max-message-bytes and retention-time separately. This way we can use the max message bytes opts value for the topic and the producer
> fix: [ENG-1638] producer max message bytes

- .github/workflows/ci-kafka.yml
- docker-compose.kafka.kgox.yml
- docker-compose.kgox.yml
- pubsubx/admin_client.go
- pubsubx/inmemory/noop_admin_client.go
- pubsubx/kgox/admin_client_impl.go
- pubsubx/kgox/consumer.go
- pubsubx/kgox/consumer_test.go
- pubsubx/kgox/event_retry_handler.go
- pubsubx/kgox/event_retry_handler_test.go
- pubsubx/kgox/poison_queue_handler.go
- pubsubx/kgox/pubsub.go
- pubsubx/kgox/test_helper.go
- pubsubx/messagex/topic.go
- pubsubx/messagex/topic_test.go
Since not all consumer of this library will use AutoTopicCreation flag in the event queue system, this solution here is to allow retry topic creation when we subscribe to a topic. It dynamically creates the topic and handles topics that already exists.
> fix: refactor event retry logic in `kgox` to manually create the retry topic instead of relying on auto-retry

- pubsubx/admin_client.go
- pubsubx/config.schema.json
- pubsubx/inmemory/noop_admin_client.go
- pubsubx/inmemory/pubsub.go
- pubsubx/kgox/admin_client_impl.go
- pubsubx/kgox/admin_client_impl_test.go
- pubsubx/kgox/consumer.go
- pubsubx/kgox/poison_queue_handler.go
- pubsubx/kgox/pubsub.go
- pubsubx/messagex/topic.go
- pubsubx/messagex/topic_test.go
Implement DeleteGroup and DeleteGroups in the admin client of `kgox` to support deleting the retry topic assigned to the groups. Also add the `DeleteTopic(s)WithRetryTopics` to allow deleting all related topics if the main topic is deleted.
> feat: [ENG-1749] add DeleteGroup and DeleteGroups admin client override for `kgox` and DeleteTopic(s)WithRetryTopics

- pubsubx/kgox/poison_queue_handler.go
- pubsubx/kgox/poison_queue_handler_test.go
Add the logic to consume the poison queue
This logic makes sure to take all the result up to the latest offset when the consumption is done.
The consumption record count is non-deterministic because we are consuming by batch the records and we complete when the new batch includes the final offset define when the consumption started. We can end up with a small amount of records on top of the final offset, but the logic makes sure that we stop when we include that offset.
The logic intend to make a single execution with all the records to the handler. This is to prevent scenario where we can push back more event on the queue and accidentally consume them.
> feat: [ENG-1786] add the ConsumeQueue to the poisonQueueHandler to allow consuming the poison queue

- logrusx/hooks.go
- logrusx/hooks_test.go
Add a hook implementation that retrieve the RequestId from the context and puts it in the fields of the Logger. The hook is made to never throw an error to not break logging.
> feat: Add RequestIdHook that adds the RequestId from the context to the logger fields

- httpx/header.go
- httpx/header_test.go
Add `x-clinia-healthy` header information and function to help use it within `x`
> feat: Add httpx x-clinia-healthy constants and functions

- httpx/header.go
- httpx/header_test.go
Fix of the helper function to updater header on the response we are writing instead of the request we are receiving.
> fix: Helper function in httpx should update ResponseWriter instead of Request

- elasticx/index_name.go
- elasticx/index_name_test.go
This PR modifies the indexName methods to support index with more than 3 parts. 
For example, for the index `clinia-engines~atlas~source~1.resources.clinic` the name should be `source~1.resources.clinic` instead of only `source`
> fix: index name methods

- .github/workflows/ci-kafka.yml
- configx/provider.go
- docker-compose.ci.kgox.yml
- go.mod
- pubsubx/config.go
- pubsubx/config.schema.json
- pubsubx/kgox/consumer.go
- pubsubx/kgox/consumer_test.go
- pubsubx/kgox/test_helper.go
This is the first iteration of improvement for the manual commit logic for the consumer. The current implementation is trivial as it execute all the records the consumer received in the poll batch and then only commit all the record that were processed at the end. This allows to prevent issue such as : 
- Network failure while processing that prevent the record to actually be handled
- Node failure where the instance that was executing the logic simply fails and never reach completion
Current usage of the consumer is mostly only using a single partition, therefore the rebalancing while polling issue is not currently an issue. But to ensure better performance and reduce the possibility of processing multiple time a same event, we should look into a followup to allow async execution of the …
> feat: [ENG-1726] Add the configuration and logic to use manual commit instead of auto-commit

- Makefile
- docker-compose.kgox.yml
- pubsubx/config.go
- pubsubx/kgox/consumer.go
- pubsubx/kgox/consumer_test.go
- pubsubx/kgox/test_helper.go
Refactors a bit the current tests we have for `kgox`.
This also makes the `consumer.Close()` method a graceful stop that will wait until the current execution is finished before closing
> chore: [ENG-2062] kgox tests & reliability

- docker-compose.kgox.yml
- pubsubx/kgox/consumer.go
- pubsubx/kgox/consumer_test.go
- pubsubx/kgox/event_retry_handler_test.go
- pubsubx/kgox/poison_queue_handler_test.go
- pubsubx/kgox/publisher_test.go
- pubsubx/kgox/pubsub.go
- pubsubx/kgox/pubsub_logger.go
- pubsubx/kgox/pubsub_logger_test.go
- pubsubx/kgox/test_helper.go
This allows kgo to log using the same log level as the logrusx logger. This adds useful debugging information on failure and on connection.
Example :
```
INFO[2025-01-13T15:08:02-05:00] immediate metadata update triggered           audience=application pubsub.why=querying metadata for consumer initialization service_name=test service_version=v1
INFO[2025-01-13T15:08:02-05:00] immediate metadata update triggered           audience=application pubsub.why=forced load because we are producing to a topic for the first time service_name=test service_version=v1
INFO[2025-01-13T15:08:02-05:00] producing to a new topic for the first time, fetching metadata to learn its partitions  audience=application pubsub.topic=demo-test.test-topic1 service_name=test service_version=v1 …
```
> feat: [ENG-2103] Add kgox logger

- pubsubx/admin_client.go
- pubsubx/inmemory/noop_admin_client.go
- pubsubx/kgox/consumer.go
- pubsubx/kgox/event_retry_handler_test.go
- pubsubx/kgox/poison_queue_handler_test.go
- pubsubx/messagex/topic.go
- pubsubx/messagex/topic_test.go
Removes the error-prone `DeleteTopic` and fix the topic name validation that does not respect our current patterns.
> fix: [ENG-2688] Delete topics

- pubsubx/messagex/reference_tracer.go
- pubsubx/messagex/reference_tracer_impl.go
This PR adds the `messagex.MessageReferenceTracer` that will allow referential tracing with an original message trace.
> feat: [ENG-2610] Adds the MessageReferenceTracer

- errorx/error.go
- errorx/error_type.go
This PR is an improvement for all the errors like `InternalErrorf`. Some error messages are straight forward strings and they do not need an `fmt` formatter. 
`fmt` is a great package but it uses reflection and causes a heap allocation. 
So if we do something like the below can cause un-necessary heap allocation and n this case we do not even use fmt
```
errMessage := "failed to commit transaction"
InternalErrorf(errMessage)
```
```
BenchmarkInternalErrorf-10       57875641            20.71 ns/op        4 B/op          1 allocs/op
BenchmarkInternalError-10        1000000000           0.2701 ns/op          0 B/op          0 allocs/op
```
If you see the benchmark, not using fmt will help us save some important CPU cycles and heap allocation
> feat: Add support for non formatted errors to improve perf

- pubsubx/messagex/reference_tracer_impl.go
This PR fixes the edge case where message does not have trace in their context.
> fix: reference with empty traceContext generate parentless span

- elasticx/index.go
- elasticx/index_impl.go
- elasticx/index_test.go
- elasticx/update_query_response.go
This PR adds `UpdateDocumentsByQuery` to index interface. It applies the `updateScript` to the documents that match the provided query.
> feat: [ENG-3100] elasticx update by query support

- elasticx/index.go
- elasticx/index_impl.go
This PR fixes the `DefaultDocumentOptions` that was initialized as a shared pointer.
Every subsequent usage to it would use the last mutated value (and also not work well in parallel)
> fix: [ENG-3209] Fix elasticx document options

- .github/workflows/test.yml
- docker-compose.yml
- elasticx/engine.go
- elasticx/engine_impl.go
- elasticx/engine_test.go
This PR inmplements the elastic scroll endpoint as part of our engine interface. It is a simple endpoint without much business logic. Essentially proxying the method to es client.
> feat: [AT-33] update Elasticsearch and Kibana images to latest versions; add Scroll method to Engine interface and implementation with tests

- pubsubx/kgox/consumer.go
- pubsubx/kgox/consumer_test.go
This PR adds the message of the recovered panic into the internal error returned and the log. I've also added an assertion in the corresponding unit test to catch that change
> feat: [ENG-3986] Added recovered panic message to error and log in kgox package
