.github/workflows/test.yml, arangox/migration_test.go, arangox/migrator.go, configx/provider_watch_test.go, docker-compose.yml, elasticx/client_test.go, elasticx/engine_test.go, elasticx/index_test.go, go.mod, go.sum
This PR adds the ability to scope the Arango migrator to a specific package. Therefore a project could support multiple independent sequences of migrations and lifecycles.
=> feat(Arangox): scoped pkg migrations

arangox/index.go, arangox/types.go, errorx/error.go, errorx/error_test.go, errorx/error_type.go, funcx/first.go, testx/http.go, tuplex/tuple.go
=> feat: arango migration types, errorx, testx

errorx/error.go, errorx/error_type.go
This PR adds an error type `NotImplemented`
=> feat: [PROD-3799] add error type 'not-implemented'

slicex/append.go, slicex/append_test.go
Create a custom append function which always returns a new slice which is a copy of a given entry slice with element append
=> feat: Add slicex Append function

logrusx/helper.go
This PR add traces fields in logging
=> feat: [ENG-215] Add Traces fields in logging

errorx/error.go, errorx/error_type.go
this PR makes clinia error compatible with https://chromium.googlesource.com/external/github.com/grpc/grpc/+/refs/tags/v1.21.4-pre1/doc/statuscodes.md
=> chore: review errors

stringsx/random.go, stringsx/random_test.go
This PR adds a Random function to stringsx that generates a random string with a required length
=> feat: random string

pubsubx/kafkax/batch_message_handler.go
Discovered some bottlenecks for the batch consumer, especially when consuming from multiple batch consumers.
With this PR, we:
- avoid starting timers until batch handlers receive at least one message (reduces a lot of overhead)
- ensure proper cleanup when exiting ProcessMessages
=> fix: batch consumer

otelx/jaeger.go, otelx/otlp.go, otelx/stdout.go, otelx/tracer_config.go, pubsubx/inmemory.go, pubsubx/kafka.go, pubsubx/kafkax/batch_message_handler.go, pubsubx/kafkax/publisher.go, pubsubx/publisher.go
Pretty straightforward:
- adds the ability to configure the tracing span limits (to add events to spans);
- adds a BulkPublish in pubsub
=> feat: Bulk publish messages & configurable span limits

arangox/types.go
This PR modifies the arango graph params to remove the indexes. The collection (vertex and edge) will now be created first and then added to the graph
=> feat: modify arango graph params

pubsubx/kafka.go, pubsubx/pubsub.go
Since we were using a `sync.Map` for our subscriber groups, whenever a subscriber was closed it would stay in an invalid state that would never be able to Subscribe again. This ensures that whenever we close a subscriber from the subs group, we remove it from the sync.map and allow recreating one.
=> fix: Kafka consumer group close

pubsubx/kafkax/subscriber.go
Adds a sync check for the subscriber.close flag
=> fix: Protected close flag

arangox/migration_test.go, arangox/migrator.go
Quick PR that allows to use a `dryRun` flag with our migrator. This will be useful for our CLIs to validate changes before executing them.
Other insignificant changes:
=> feat: Add a dry-run flag to the arangox migrator

elasticx/bulk/action.go, elasticx/bulk/operation.go, elasticx/bulk/option.go, elasticx/engine.go, elasticx/engine_impl.go, elasticx/engine_test.go, elasticx/migrate/migration_test.go, elasticx/migrate/migrator.go, elasticx/msearch/item.go, elasticx/msearch/option.go, elasticx/search/option.go
Simple PR to support es query params in the engine bulk method
=> feat: support es bulk query params

elasticx/error.go, elasticx/index.go, elasticx/index_impl.go, elasticx/index_test.go, elasticx/migrate/migrator.go, elasticx/upsert_response.go
This PR replace the `ReplaceDocument` method for an `UpsertDocument` method. It also returns if the record was created or updated.
=> feat: upsert document

elasticx/engine_impl.go, elasticx/engine_test.go
This PR fixes a wrong implementation in elastic bulk update operation, op needs to be wrapped in doc field
=> fix: elastic bulk update operation

elasticx/engine_impl.go, elasticx/engine_test.go
This PR adds validation for the search window size
=> feat: validate search window size

pubsubx/kgox/consumer_test.go, pubsubx/kgox/marshaler.go, pubsubx/kgox/publisher.go, pubsubx/messagex/message.go
This PR adds propagation of trace context from message
=> feat: [ENG-1706] kgox propagate trace in record context

pubsubx/kgox/marshaler.go, pubsubx/messagex/message.go
This PR implements methods in messagex.message to handle traceContext
=> feat: trace context func in messagex.message

configx/provider.go, pubsubx/config.go, pubsubx/config.schema.json, pubsubx/config_test.go, pubsubx/kgox/consumer.go, pubsubx/kgox/consumer_test.go, pubsubx/kgox/poison_queue_handler.go, pubsubx/kgox/poison_queue_handler_test.go, pubsubx/kgox/pubsub.go, pubsubx/kgox/test_helper.go
- **Add poison queue**
- **feat: intergate the poison queue**
- **Add auto creation of the poison queue topic on pubsub creation**
=> feat: [ENG-1724] add poison queue implementation and configuration for kgox

pubsubx/kgox/admin_client_impl.go, pubsubx/kgox/admin_client_impl_test.go, pubsubx/kgox/consumer.go, pubsubx/kgox/event_retry_handler.go, pubsubx/kgox/event_retry_handler_test.go, pubsubx/kgox/pubsub.go, pubsubx/kgox/test_helper.go
Simply add a ping call to ping the brokers and verify that one is healthy and that the connection can be made
=> feat: [ENG-1663] Improve the pubsub healthcheck to ping the brokers

errorx/error.go, errorx/error_type.go
New error type to be used for HTTP 413.
=> chore: [ENG-1837] payload too large error

otelx/otlp.go, otelx/tracer.go
Quick PR that allows to use the actual tracer provider when it is set.
=> feat: Return real tracer provider when available

pubsubx/kgox/consumer.go, pubsubx/kgox/event_retry_handler.go, pubsubx/kgox/poison_queue_handler.go, pubsubx/kgox/pubsub.go
Add the missing WithContext for the logging in `kgox`
=> chore: [ENG-1824] add missing `WithContext` for logger in `kgox`

mathx/bytes.go, mathx/bytes_test.go, reflectx/size_of.go, reflectx/size_of_test.go
Quick PR to add our `reflectx` package to `x`.
=> fix:[ENG-1797] Introduce reflectx package

configx/provider.go, logrusx/config.schema.json, otelx/meter.schema.json, otelx/tracer.schema.json, pubsubx/config.schema.json, tritonx/config.go, tritonx/config.schema.json
Quick PR to add the missing specs in the config schemas.
=> chore: [ENG-2055] Add missing config schemas

elasticx/index.go, elasticx/index_impl.go, elasticx/index_test.go
This PR adds a method to update an elastic index mappings
=> feat: [ENG-2095] update index mappings

logrusx/log_fields.go, otelx/prometheus_labels.go, otelx/prometheus_labels_test.go
Quick PR that adds the `NewPrometheusLabels` function.
=> feat: [ENG-1784] Prometheus labels mapper

logrusx/helper.go, logrusx/helper_test.go
This PR modifies the logger `withError` method to include the clinia error details
=> feat: [ENG-2160] log error details

retryx/example_test.go, retryx/retry.go, retryx/retry_options.go, retryx/retry_test.go
Adds a simple `retryx` package that we can reuse across our apps for simpler retry mechanisms
=> feat: retryx package

pubsubx/kgox/consumer.go
Quick PR that adds a log when abort subscribe error happens.
=> fix: [ENG-2683] Add log for critical error in consumer

pubsubx/kgox/consumer_rebalances_test.go
Adds tests for consumer group offsets management on close.
=> chore: [ENG-2584] Add consumer test

go.mod, go.sum
* Upgrade go-elasticsearch to v8.17.1
* Upgrade elastic-transport-go to v8.6.1
* Add prometheus/client_golang v1.20.4 as a direct dependency
=> chore: update dependencies in go.mod and go.sum

testx/http.go
Quick PR that allows for the context to be set in our `testx` package.
=> feat: Add WithContext to testx

elasticx/client_impl.go, elasticx/client_test.go, elasticx/engine_impl.go, elasticx/engine_test.go, elasticx/index_impl.go, elasticx/index_name.go, elasticx/index_name_test.go, elasticx/index_test.go
This adds full index name function which enables external application to get access to the underlying elasrtic index name for use cases such as appliying filters on the index name.
=> feat(elasticx): full index name

pubsubx/messagex/consumer_group.go, pubsubx/messagex/consumer_group_test.go, pubsubx/messagex/topic.go, pubsubx/messagex/topic_test.go
Quick PR that adds missing utility functions to our `messagex` package.
=> chore: [ENG-3548] Add scope utils to messagex
